### ISSUE TITLE
always erron when running mainn.py

### ISSUE THREAD

**Issue by draco330431** [Cosmicgodalpha/alphaotpbot#1]
>python mainn.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Rebel OTP Bot 2022\mainn.py", line 33, in <module>
    bot.remove_webhook()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 590, in remove_webhook
    return self.set_webhook()  # No params resets webhook
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 437, in set_webhook
    return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates, ip_address,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 288, in set_webhook
    return _make_request(token, method_url, params=payload, files=files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found

**Comment by CoreLine76** [comment]
> > python mainn.py
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Downloads\Rebel OTP Bot 2022\mainn.py", line 33, in 
> > bot.remove_webhook()
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot__init__.py", line 590, in remove_webhook
> > return self.set_webhook()  # No params resets webhook
> > ^^^^^^^^^^^^^^^^^^
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot__init__.py", line 437, in set_webhook
> > return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates, ip_address,
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 288, in set_webhook
> > return _make_request(token, method_url, params=payload, files=files)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
> > json_result = _check_result(method_name, result)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\apihelper.py", line 189, in _check_result
> > raise ApiTelegramException(method_name, result, result_json)
> > telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found

https://github.com/CoreLine76/OTP-BYPASS-and-SMS-BOT-V-3
